### ISSUE TITLE
Hifiasm and speed up

### ISSUE THREAD

**Issue by Sebastien-Raguideau** [vgteam/GetBlunted#36]
Hello,

First of all, this is really useful thanks for this tool.

I'm trying to use it on Hifiasm graphs. I saw issue#35 and while waiting for correct cigar as output of Hifiasm I implemented a small pipeline for edge realignment. 

My issue is about speed. In a gfa with about 100 edge and 100 nodes with mean overlap of 10000, get_blunted takes about 30 min to run. This is a relatively simple graph and I would like to work on a more complex graph with 58000 nodes and 46000 edges.

So instead of an issue this is rather a shameless feature request and I would like to know if you could do something for speed up. I was thinking that maybe knowing that the cigar is correct could allow to skip or speed up POA? Or maybe being able to use multiple threads to have concurrent POA running would help?

Best,
Seb

**Comment by rlorigro** [comment]
Hi Seb,

Yes this has been something we've been thinking about improving for a while. 

```
knowing that the cigar is correct could allow to skip or speed up POA
```
This has been implemented for any case in which the overlaps are all 100% matches in a biclique cover. It could potentially be expanded to more cases though. Could you share an example GFA?

However, in the case where you have indels and more than 2 sequences, there is no guarantee that the pairwise alignments are internally consistent and can be used to construct a multiple sequence alignment.

Multithreading is certainly an option, but we would prefer to just use a more efficient alignment method, so @jeizenga and I are discussing integrating abPOA to replace SPOA.

**Comment by Sebastien-Raguideau** [comment]
[Here](https://github.com/vgteam/GetBlunted/files/8079330/example.tar.gz) is the full genome assembly I have been looking at plus a minimal example with 2 unitigs.  On the minimal example, the initial cigar was `12463M`, which allow to experience first-hand what happens when doing global alignment on mismatched regions. What I came up with my script is `12103M1D15M1S16M326D` and starting from this POA prefers the following  `3S12100M1D15M1S17M2S8M316D`. 
 
I would need to look further into it, but I am surprised that POA is skipped on full match. Out of my ~100 edges, only 6 are problematic and need rectification with indel and substitutions. The minimal example I joined run in 30 sec. Again, didn't test it, but with only 6 that would be 5 minutes at most, then the 25 minutes left would be spent skipping POA? Verbose, says it's all alignment.

Yes I agree, with more than 2 sequences, it is unclear what pairwise alignment can contribute to multiple sequence alignment.

**Comment by rlorigro** [comment]
I looked at how we are handling those overlaps, and the issue is that there are exact matches, but not every overlap in every biclique cover are the same length. Admittedly it is a bit lazy, but I did not implement handling for those cases

**Comment by rlorigro** [comment]
@Sebastien-Raguideau do you know whether the slow runtime you mentioned in issue #37 is from alignment? or some other step?

**Comment by Sebastien-Raguideau** [comment]
It is also from alignment. I launched it on the 24th and it is still running, so I'm thinking bug, rather than slow, but maybe it's just slow.
On my whole dataset there are only 2 subgraphs with that issue. One rather small with 101 edges and another 10 time the size. 
[Here they are.](https://github.com/vgteam/GetBlunted/files/8168454/long_run.tar.gz)

**Comment by jeizenga** [comment]
I put some work into speeding this up. I can run locally on the two subgraphs you highlighted within a few minutes, so hopefully this resolves the bottleneck. I'll be interested to hear about your experiences genome-wide.

**Comment by Sebastien-Raguideau** [comment]
Thanks, this is stunningly faster. On the full assembly graph alignment took 4.6 hours. Though, in the end it aborted at the "Splicing overlapping overlap node" step with an error message identical to #37.
