### ISSUE TITLE
Error blunting GFA

### ISSUE THREAD

**Issue by JoshuaDanielRubin** [vgteam/GetBlunted#47]
Hello, 

I am very eager to try this program but I have encountered an issue. I have a GFA file I know to be valid, made from PGGB. However when I run

`get_blunted -V -i [GFA file]`

I see the following:

```
[get_blunted : 0.0 s elapsed] Reading GFA...
[get_blunted : 0.0 s elapsed] Computing adjacency components...
[get_blunted : 0.0 s elapsed] Total adjacency components: 7009
[get_blunted : 0.0 s elapsed] Computing biclique covers...
[get_blunted : 0.0 s elapsed] Total biclique covers: 8151
[get_blunted : 0.0 s elapsed] Duplicating node termini...
WARNING: 0 length overlap is ignored in duplicator
WARNING: 0 length overlap is ignored in duplicator
WARNING: 0 length overlap is ignored in duplicator
WARNING: 0 length overlap is ignored in duplicator
WARNING: 0 length overlap is ignored in duplicator
WARNING: 0 length overlap is ignored in duplicator
WARNING: 0 length overlap is ignored in duplicator
WARNING: 0 length overlap is ignored in duplicator
WARNING: 0 length overlap is ignored in duplicator
WARNING: 0 length overlap is ignored in duplicator
WARNING: 0 length overlap is ignored in duplicator
WARNING: 0 length overlap is ignored in duplicator
WARNING: 0 length overlap is ignored in duplicator
WARNING: 0 length overlap is ignored in duplicator
WARNING: 0 length overlap is ignored in duplicator
WARNING: 0 length overlap is ignored in duplicator
WARNING: 0 length overlap is ignored in duplicator
WARNING: 0 length overlap is ignored in duplicator
WARNING: 0 length overlap is ignored in duplicator
WARNING: 0 length overlap is ignored in duplicator
WARNING: 0 length overlap is ignored in duplicator
WARNING: 0 length overlap is ignored in duplicator
WARNING: 0 length overlap is ignored in duplicator
terminate called after throwing an instance of 'std::out_of_range'
  what():  at: key not present
Aborted (core dumped)

```

**Comment by rlorigro** [comment]
Hi Joshua, 

Is there any portion of the graph that you would be willing to share which reproduces this error? you can try using the [extract_subgraph](https://github.com/vgteam/GetBlunted/blob/master/src/executable/extract_subgraph.cpp) executable on your GFA to get a smaller test region. 

You would need to compile the library to find that executable in the build directory. Or else I can try making a static one if that is not possible.

**Comment by JoshuaDanielRubin** [comment]
Thank you so much for your very prompt response. You can find the GFA (only around 200 MB) here : https://drive.google.com/drive/folders/1-_RTTozPBjDcKMSANwJNRI5qd0_tO14E?usp=sharing

I will try to see if I can get it to work on a subgraph.

**Comment by rlorigro** [comment]
Hi Joshua, it appears that your GFA doesn't have any overlaps. For example, here is an excerpt of your L lines:
```
L       6894    +       6896    +       *
L       7989    +       7990    +       *
L       7989    +       7991    +       *
L       10082   +       10083   +       *
L       10082   +       10084   +       *
L       8051    +       8053    +       *
L       8051    +       8052    +       *
L       5082    +       5084    +       *
L       5082    +       5083    +       *
```
The `*` is the field where you would observe a cigar string which describes an overlap alignment between two nodes. However, in this case it indicates that there is no overlap, same as `0M` would.

**Comment by JoshuaDanielRubin** [comment]
Ah I see! That solves the problem then. Thank you for the explanation.

**Comment by rlorigro** [comment]
No worries. We will try to make GetBlunted handle this situation more gracefully
