### ISSUE TITLE
Issues with compiling due to updated abPOA

### ISSUE THREAD

**Issue by hmusta** [vgteam/GetBlunted#48]
Compilation on the latest commit fails for me when I use the provided instructions (`cmake .. && make`).

The CMakeLists.txt seems to be checking out the latest commit of abPOA from a few days ago, which broke compatibility.

This patch fixes compilation for me.
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3211822..da5a179 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -235,7 +235,7 @@ else()
     # Download or update library as an external project
     ExternalProject_Add(project_abPOA
             GIT_REPOSITORY https://github.com/yangao07/abPOA.git
-            GIT_TAG main
+            GIT_TAG bfe4ac0a4945ed3eadf68282776fc816b299947e
             PREFIX ${CMAKE_CURRENT_BINARY_DIR}/external/
             CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${CMAKE_SOURCE_DIR}/external/abPOA/ -DCMAKE_INSTALL_LIBDIR=${CMAKE_SOURCE_DIR}/external/abPOA/lib
             BUILD_IN_SOURCE True
```

I'm wondering if this is the right approach.

**Comment by rlorigro** [comment]
I think this was actually intended to be fixed already, but we missed that branch of the conditional, which contains copied code in CMakeLists.txt

I updated the main branch with the hardcoded git tag. But you can also always use a pre-compiled release if you are on ubuntu/centOS.
