### ISSUE TITLE
"Aligning overlaps" fails with segmentation fault on Verkko graph

### ISSUE THREAD

**Issue by rebeccaserramari** [vgteam/GetBlunted#49]
Hi, 

I was trying to use GetBlunted on a gfa resulting from Verkko, but ran into a bunch of errors which look like memory issues within the tool.
I run GetBlunted using `./get_blunted -V -i input.gfa`. For the whole graph, I get the following output:
```
[get_blunted : 0.0 s elapsed] Reading GFA...
[get_blunted : 24.0 s elapsed] Computing adjacency components...
[get_blunted : 24.0 s elapsed] Total adjacency components: 15689
[get_blunted : 24.0 s elapsed] Computing biclique covers...
[get_blunted : 24.0 s elapsed] Total biclique covers: 11028
[get_blunted : 24.0 s elapsed] Duplicating node termini...
WARNING: 0 length overlap is ignored in duplicator **[This line is repeated several times]**
[get_blunted : 28.0 s elapsed] Harmonizing biclique edge orientations...
[get_blunted : 28.0 s elapsed] Aligning overlaps...
[SIMDMalloc] posix_memalign fail!
Size: 274877906944, Error: ENOMEM
```

For test purposes, I used an extracted component from the graph, but also on the smaller graph, I got the following error, aka segmentation fault:
```
[get_blunted : 0.0 s elapsed] Reading GFA...
[get_blunted : 1.0 s elapsed] Computing adjacency components...
[get_blunted : 1.0 s elapsed] Total adjacency components: 390
[get_blunted : 1.0 s elapsed] Computing biclique covers...
[get_blunted : 1.0 s elapsed] Total biclique covers: 410
[get_blunted : 1.0 s elapsed] Duplicating node termini...
[get_blunted : 2.0 s elapsed] Harmonizing biclique edge orientations...
[get_blunted : 2.0 s elapsed] Aligning overlaps...
Command terminated by signal 11
```
Only on very small extracted component graphs, GetBlunted finished without an error. But these contain only a handful of nodes and are therefore not relevant for my analysis. 

Any idea what causes these (apparent) memory errors? I could also send you a link to share the smaller graph which yields the segfault with you if necessary. 

I'd be grateful for any advice, as I'm really eager to get a bluntified version of my graph. 
Thank you in advance!

**Comment by jeizenga** [comment]
I suspect that the warning about the 0-length overlaps is a problem upstream in Verkko. We've seen other graphs from Verkko where the overlaps are set to 0, which is apparently a bug. I believe our team has reported this bug to the Verkko developers, but things might move faster if you request a bug fix as well.

Regarding the memory error / seg fault: yes, please do send along the smaller component graph so we can look into diagnosing the issue.

**Comment by rebeccaserramari** [comment]
I'm just realizing I had used the 'reply by mail' function by Github on this issue, but not sure how well this works.
Just to be safe that nothing gets lost, I'm copying my answer also here in the comment field

Thanks for the prompt response!
I uploaded the graph (~380 MB) here: https://drive.google.com/file/d/1T3gU4cecFC9PcRjQhc2KrG1FnMfg1rrQ/view?usp=sharing

Thanks again

**Comment by jeizenga** [comment]
I just merged a PR that should resolve the crash. Unfortunately, the fix is not exactly fast. It seems like there's no MSA library out there that does exactly what we'd want for these alignments. Hopefully this will at least unblock you though :)
